CREATE TYPE pedido_prioridad AS ENUM ('baja', 'normal', 'alta');

CREATE TYPE pedido_estado AS ENUM ('pendiente', 'aprobado', 'finalizado');

CREATE TABLE clientes (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  numero_cliente integer GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  nombre varchar(120) NOT NULL,
  apellido varchar(120) NOT NULL,
  direccion varchar(255),
  telefono varchar(50),
  mail varchar(255),
  fecha_alta timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE pedidos (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  numero_pedido integer GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  cliente_id integer REFERENCES clientes(id) ON DELETE SET NULL,
  marca_id integer REFERENCES marcas(id),
  modelo_id integer REFERENCES modelos(id),
  motor_id integer REFERENCES motores(id),
  numero_serie_motor varchar(120) NOT NULL DEFAULT '',
  prioridad pedido_prioridad NOT NULL DEFAULT 'normal',
  estado pedido_estado NOT NULL DEFAULT 'pendiente',
  fecha_creacion timestamptz NOT NULL DEFAULT now(),
  fecha_aprobacion timestamptz,
  observaciones text,
  CONSTRAINT pedidos_aprobado_requiere_cliente
    CHECK (estado <> 'aprobado' OR cliente_id IS NOT NULL)
);

CREATE TABLE pedido_trabajos (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  pedido_id integer NOT NULL REFERENCES pedidos(id) ON DELETE CASCADE,
  trabajo_id integer NOT NULL REFERENCES trabajos(id),
  UNIQUE (pedido_id, trabajo_id)
);

CREATE INDEX idx_clientes_numero_cliente ON clientes(numero_cliente);
CREATE INDEX idx_clientes_busqueda ON clientes (lower(apellido), lower(nombre));
CREATE INDEX idx_pedidos_numero_pedido ON pedidos(numero_pedido);
CREATE INDEX idx_pedidos_cliente_id ON pedidos(cliente_id);
CREATE INDEX idx_pedidos_estado_prioridad ON pedidos(estado, prioridad);
CREATE INDEX idx_pedido_trabajos_pedido_id ON pedido_trabajos(pedido_id);
CREATE INDEX idx_pedido_trabajos_trabajo_id ON pedido_trabajos(trabajo_id);

