export const ENGINE_ICON_OPTIONS = [
  "009-car-engine-6.svg",
  "010-car-engine-5.svg",
  "011-car-engine-4.svg",
  "018-car-engine-3.svg",
  "022-engine-2.svg",
  "029-car-engine-2.svg",
  "033-car-engine-1.svg",
  "040-car-engine.svg",
  "042-engine-1.svg",
  "049-engine.svg",
  "037-piston-1.svg",
  "048-piston.svg",
  "020-crankshaft.svg",
  "041-spark-plug.svg",
  "003-turbo.svg",
  "023-gears.svg",
  "030-gear.svg",
  "007-belt-3.svg",
  "038-belt-2.svg",
  "046-belt-1.svg",
  "047-belt.svg",
  "050-air-filter.svg",
  "012-radiator-1.svg",
  "019-radiator.svg",
  "034-fan-1.svg",
  "039-fan.svg",
  "035-cooler.svg",
  "045-gasoline.svg",
  "026-power.svg",
  "002-exhaust-pipe.svg",
  "032-pipe.svg",
  "017-battery.svg",
  "044-transmission.svg",
  "001-gearshift-1.svg",
  "024-gearshift.svg",
  "008-speedometer.svg",
  "013-steering-wheel.svg",
  "015-chassis.svg",
  "043-suspension.svg",
  "014-shock-absorber-1.svg",
  "027-shock-absorber.svg",
  "004-brake-2.svg",
  "021-brake-1.svg",
  "028-brake.svg",
  "016-wheel.svg",
  "036-tire.svg",
  "005-alloy-wheel-1.svg",
  "006-alloy-wheel.svg",
  "031-car-lights.svg",
  "025-windscreen.svg",
] as const;

export type EngineIconName = (typeof ENGINE_ICON_OPTIONS)[number];

const ENGINE_ICON_LABELS: Record<EngineIconName, string> = {
  "001-gearshift-1.svg": "Palanca de cambios",
  "002-exhaust-pipe.svg": "Caño de escape",
  "003-turbo.svg": "Turbo",
  "004-brake-2.svg": "Freno",
  "005-alloy-wheel-1.svg": "Llanta de aleación",
  "006-alloy-wheel.svg": "Llanta",
  "007-belt-3.svg": "Correa",
  "008-speedometer.svg": "Velocímetro",
  "009-car-engine-6.svg": "Motor",
  "010-car-engine-5.svg": "Motor",
  "011-car-engine-4.svg": "Motor",
  "012-radiator-1.svg": "Radiador",
  "013-steering-wheel.svg": "Volante",
  "014-shock-absorber-1.svg": "Amortiguador",
  "015-chassis.svg": "Chasis",
  "016-wheel.svg": "Rueda",
  "017-battery.svg": "Batería",
  "018-car-engine-3.svg": "Motor",
  "019-radiator.svg": "Radiador",
  "020-crankshaft.svg": "Cigüeñal",
  "021-brake-1.svg": "Freno",
  "022-engine-2.svg": "Block",
  "023-gears.svg": "Engranajes",
  "024-gearshift.svg": "Caja de cambios",
  "025-windscreen.svg": "Parabrisas",
  "026-power.svg": "Potencia",
  "027-shock-absorber.svg": "Amortiguador",
  "028-brake.svg": "Freno",
  "029-car-engine-2.svg": "Motor",
  "030-gear.svg": "Engranaje",
  "031-car-lights.svg": "Luces",
  "032-pipe.svg": "Caño",
  "033-car-engine-1.svg": "Motor",
  "034-fan-1.svg": "Ventilador",
  "035-cooler.svg": "Enfriador",
  "036-tire.svg": "Neumático",
  "037-piston-1.svg": "Pistón",
  "038-belt-2.svg": "Correa",
  "039-fan.svg": "Ventilador",
  "040-car-engine.svg": "Motor",
  "041-spark-plug.svg": "Bujía",
  "042-engine-1.svg": "Motor",
  "043-suspension.svg": "Suspensión",
  "044-transmission.svg": "Transmisión",
  "045-gasoline.svg": "Combustible",
  "046-belt-1.svg": "Correa",
  "047-belt.svg": "Correa",
  "048-piston.svg": "Pistón",
  "049-engine.svg": "Motor",
  "050-air-filter.svg": "Filtro de aire",
};

export function formatEngineIconLabel(fileName: EngineIconName) {
  return ENGINE_ICON_LABELS[fileName];
}

export function getEngineIconSrc(fileName: EngineIconName) {
  return `/engine-icons/${fileName}`;
}

export function isEngineIconName(value: string | null | undefined): value is EngineIconName {
  return ENGINE_ICON_OPTIONS.some((option) => option === value);
}
